from networking.McPackets import serverbound, clientbound
from common.types.enums import McState

lut_serverbound = {
	McState.Handshaking: {
		0x00: serverbound.handshaking.Handshake,
		0xFE: serverbound.handshaking.LegacySeverPing
	},
	McState.Status: {
		0x00: serverbound.status.Request,
		0x01: serverbound.status.Ping
	},
	McState.Login: {
		0x00: serverbound.login.Start,
		0x01: serverbound.login.EncryptionResponse,
	},
	McState.Play: {
		0x00: serverbound.play.TeleportConfirm,
		0x01: serverbound.play.TabComplete,
		0x02: serverbound.play.ChatMessage,
		0x03: serverbound.play.ClientStatus,
		0x04: serverbound.play.ClientSettings,
		0x05: serverbound.play.ConfirmTransaction,
		0x06: serverbound.play.EnchantItem,
		0x07: serverbound.play.ClickWindow,
		0x08: serverbound.play.CloseWindow,
		0x09: serverbound.play.PluginMessage,
		0x0A: serverbound.play.UseEntity,
		0x0B: serverbound.play.KeepAlive,
		0x0C: serverbound.play.PlayerPosition,
		0x0D: serverbound.play.PlayerLookAndPosition,
		0x0E: serverbound.play.PlayerLook,
		0x0F: serverbound.play.Player,
		0x10: serverbound.play.VehicleMove,
		0x11: serverbound.play.SteerBoat,
		0x12: serverbound.play.PlayerAbilities,
		0x13: serverbound.play.PlayerDigging,
		0x14: serverbound.play.EntityAction,
		0x15: serverbound.play.SteerVehicle,
		0x16: serverbound.play.ResourcePackStatus,
		0x17: serverbound.play.HeldItemChange,
		0x18: serverbound.play.CreativeInventorAction,
		0x19: serverbound.play.UpdateSign,
		0x1A: serverbound.play.Animation,
		0x1B: serverbound.play.Spectate,
		0x1C: serverbound.play.PlayerBlockPlacement,
		0x1D: serverbound.play.UseItem,
	}
}

lut_clientbound = {
	McState.Handshaking: {
	},
	McState.Status: {
		0x00: clientbound.status.Response,
		0x01: clientbound.status.Pong,
	},
	McState.Login: {
		0x00: clientbound.login.Disconnect,
		0x01: clientbound.login.EncryptionRequest,
		0x02: clientbound.login.Success,
		0x03: clientbound.login.SetCompression,
	},
	McState.Play: {
		0x00: clientbound.play.SpawnObjectV107,
		0x01: clientbound.play.SpawnExperienceOrb,
		0x02: clientbound.play.SpawnGlobalEntity,
		0x03: clientbound.play.SpawnMob107,
		0x04: clientbound.play.SpawnPainting,
		0x05: clientbound.play.SpawnPlayer,
		0x06: clientbound.play.Animation,
		0x07: clientbound.play.Statistics,
		0x08: clientbound.play.BlockBreakAnimation,
		0x09: clientbound.play.UpdateBlockEntity,
		0x0A: clientbound.play.BlockAction,
		0x0B: clientbound.play.BlockChange,
		# 0x0C: clientbound.play., # TODO: Nope not tonight see: boss_bar,
		0x0D: clientbound.play.ServerDifficulty,
		0x0E: clientbound.play.TabComplete,
		0x0F: clientbound.play.ChatMessage,
		0x10: clientbound.play.MultiBlockChange,
		0x11: clientbound.play.ConfirmTransaction,
		0x12: clientbound.play.CloseWindow,
		0x13: clientbound.play.OpenWindow,
		0x14: clientbound.play.WindowItems,
		0x15: clientbound.play.WindowProperty,
		0x16: clientbound.play.SetSlot,
		0x17: clientbound.play.SetCooldown,
		0x18: clientbound.play.PluginMessage,
		0x19: clientbound.play.NamedSoundEffect,
		0x1A: clientbound.play.Disconnect,
		0x1B: clientbound.play.EntityStatus,
		0x1C: clientbound.play.Explosion,
		0x1D: clientbound.play.UnloadChunk,
		0x1E: clientbound.play.ChangeGameState,
		0x1F: clientbound.play.KeepAlive,
		0x20: clientbound.play.ChunkDataV107,
		0x21: clientbound.play.Effect,
		0x22: clientbound.play.Particle,
		0x23: clientbound.play.JoinGame,
		# 0x24: clientbound.play., # TODO: Nope not tonight see: map,
		0x25: clientbound.play.EntityRelativeMove,
		0x26: clientbound.play.EntityLookAndRelativeMove,
		0x27: clientbound.play.EntityLook,
		0x28: clientbound.play.Entity,
		0x29: clientbound.play.VehicleMove,
		0x2A: clientbound.play.OpenSignEditor,
		0x2B: clientbound.play.PlayerAbilitites,
		0x2C: clientbound.play.CombatEvent,
		# 0x2D: clientbound.play., # TODO: Nope not tonight see: player list item
		0x2E: clientbound.play.PositionAndLook107,
		0x2F: clientbound.play.UseBed,
		0x30: clientbound.play.DestroyEntities,
		0x31: clientbound.play.RemoveEntityEffect,
		0x32: clientbound.play.RessourcePackSend,
		0x33: clientbound.play.Respawn,
		0x34: clientbound.play.EntityHeadLook,
		# 0x35: clientbound.play., # TODO: Nope not tonight see: worldborder
		0x36: clientbound.play.Camera,
		0x37: clientbound.play.HeldItemChanged,
		0x38: clientbound.play.DisplayScoreboard,
		0x39: clientbound.play.EntityMetadata,
		0x3A: clientbound.play.AttachEntity,
		0x3B: clientbound.play.EntityVelocity,
		0x3C: clientbound.play.EntityEquipment,
		0x3D: clientbound.play.SetExperience,
		0x3E: clientbound.play.UpdateHealth,
		0x3F: clientbound.play.ScoreboardObjective,
		0x40: None,
		# 0x41: None, # TODO: Nope not tonight see: teams
		0x42: clientbound.play.UpdateScore,
		0x43: clientbound.play.SpawnPosition,
		0x44: clientbound.play.TimeUpdate,
		# 0x45: clientbound.play., # TODO: Nope not tonight see: title
		0x46: clientbound.play.UpdateSign,
		0x47: clientbound.play.SoundEffectV107,
		0x48: clientbound.play.PlayerListHeaderAndFooter,
		0x49: clientbound.play.CollectItem,
		0x4A: clientbound.play.EntityTeleport,
		0x4B: clientbound.play.EntityProperties,
		0x4C: clientbound.play.EntityEffect,
	}
}

proto = {
	"clientbound": lut_clientbound,
	"serverbound": lut_serverbound,
}