MINEPROXY_PROXY_REMOTE_IP = "192.168.1.33"
MINEPROXY_PROXY_REMOTE_PORT = 25565
MINEPROXY_PROXY_LISTEN_PORT = 25565
MINEPROXY_PARSE_PLAY_PACKETS = True

MINEPROXY_AUTH_USE_MICROSOFT = False
MINEPROXY_AUTH_MINECRAFT_EMAIL = "xxxxxxxxxxxxx@xxxxxxxx.xx"
MINEPROXY_AUTH_MINECRAFT_PASSWORD = "xxxxxxxxxxxxxx"
